version: '3.5'

services:

  eureka-discovery-server:
    image: eureka-discovery-server:latest
    container_name: eureka-discovery-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    volumes:
      - /data/app
    networks:
      - autostreet_shared

networks:
  autostreet_shared:
    external: true
    name: autostreet_shared